<?php include 'blocks/header.phtml'; ?>

<main>
    <div class="container-lg mt-3">
        <h1>Сайты</h1>
        <div class="table-responsive">
            <table class="table table-bordered table-hover text-nowrap" data-test="urls">
                <thead>
                    <th>ID</th>
                    <th>Имя</th>
                    <th>Последняя проверка</th>
                    <th>Код ответа</th>
                </thead>
            </table>
        </div>
    </div>
</main>

<?php include 'blocks/footer.phtml'; ?>