<?php include 'blocks/header.phtml'; ?>
<?php  if(isset($flash['success'])): ?>
    <div class="alert alert-success" role="alert"><?= htmlspecialchars($flash['success'][0]) ?></div>
<?php endif ?>
<main>
    <div class="container-lg mt-3">
        <h1>Сайт: <?= htmlspecialchars($data[0]['name']) ?></h1>
        <div class="table-responsive">
            <table class="table table-bordered table-hover text-nowrap" data-test="url">
                <tbody>
                    <tr>
                        <td>ID</td>
                        <td><?= htmlspecialchars($data[0]['id']) ?></td>
                    </tr>
                    <tr>
                        <td>Имя</td>
                        <td><?= htmlspecialchars($data[0]['name']) ?></td>
                    </tr>
                    <tr>
                        <td>Дата создания</td>
                        <td><?= htmlspecialchars($data[0]['created_at']) ?></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <h2 class="mt-5 mb-3">Проверки</h2>
        <form method="post" action="/urls/<?= htmlspecialchars($data[0]['id']) ?>/checks">
            <input type="submit" class="btn btn-primary" value="Запустить проверку">
        </form>
        <table class="table table-bordered table-hover mt-3" data-test="checks">
            <thead>
                <th>ID</th>
                <th>Код ответа</th>
                <th>h1</th>
                <th>title</th>
                <th>description</th>
                <th>Дата создания</th>
            </thead>
            <tbody>
                <?php foreach($checks as $key): ?>
                    <tr>
                        <td><?= htmlspecialchars($key['id']) ?></td>
                        <td><?= htmlspecialchars($key['status_code']) ?></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td><?= htmlspecialchars($key['created_at']) ?></td>
                    </tr>
                <?php endforeach ?>
            </tbody>
        </table>
    </div>
</main>

<?php include 'blocks/footer.phtml'; ?>
