<?php include 'blocks/header.phtml'; ?>
<?php  if(isset($flash['success'])): ?>
    <div class="alert alert-success" role="alert"><?= htmlspecialchars($flash['success'][0]) ?></div>
<?php endif ?>
<main>
    <div class="container-lg mt-3">
        <h1>Сайт: <?= htmlspecialchars($data[0]['name']) ?></h1>
        <div class="table-responsive">
            <table class="table table-bordered table-hover text-nowrap" data-test="url">
                <tbody>
                    <tr>
                        <td>ID</td>
                        <td><?= htmlspecialchars($data[0]['id']) ?></td>
                    </tr>
                    <tr>
                        <td>Имя</td>
                        <td><?= htmlspecialchars($data[0]['name']) ?></td>
                    </tr>
                    <tr>
                        <td>Дата создания</td>
                        <td><?= htmlspecialchars($data[0]['created_at']) ?></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</main>

<?php include 'blocks/footer.phtml'; ?>
